services:
  postgres:
    env_file: 
     - .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    image: postgres
  postgres_syst_part:
    env_file:
     - .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  postgres_vol_docker:
    env_file:
     - .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

secrets:
  db_password:
    file: db_password.txt

