
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "testuser"
      MONGO_INITDB_ROOT_PASSWORD: "testpassword"

  # webapp-1:
  #   image: webapp-1:latest
  #   ports:
  #     - "127.0.0.1:8080:8080"
  #   environment:
  #     MONGODB_USER: "testuser"
  #     MONGODB_PASSWORD: "testpassword"
  #     MONGODB_HOST: "mongodb"
  #     MONGODB_DATABASE: "admin"
  #   depends_on:
  #     - mongodb

  webapp-2:
    image: webapp-2:latest
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      MONGODB_USER: "myuser"
      MONGODB_PASSWORD: "mypassword"
      MONGODB_HOST: "mongodb"
      MONGODB_DATABASE: "admin"
    depends_on:
      - mongodb
